export const types = {
    SET_PLAY_WORD: 'SET_PLAY_WORD',
    VALIDATE_WORD_SUCCESS: 'VALIDATE_WORD_SUCCESS',
    VALIDATE_WORD_FAILURE: 'VALIDATE_WORD_FAILURE',
    PLAY_WORD: 'PLAY_WORD',
    RESET_PLAY_WORD: 'RESET_PLAY_WORD'
};
