export const types = {
    RESET_CHAT: 'RESET_CHAT',
    VIEW_MESSAGES: 'VIEW_MESSAGES',
    ADD_MESSAGE: 'ADD_MESSAGE',
    SEND_CHAT_SUCCESS: 'SEND_CHAT_SUCCESS',
    SEND_CHAT_FAILURE: 'SEND_CHAT_FAILURE'
}
