export const types = {
    SET_PLAY_CARD_TIMER: 'SET_PLAY_CARD_TIMER',
    SET_VOTE_CARD_TIMER: 'SET_VOTE_CARD_TIMER',
    SET_STORYTELLER_TIMER: 'SET_STORYTELLER_TIMER',
    REQUEST_NEXT_ROUND_SUCCESS: 'REQUEST_NEXT_ROUND_SUCCESS',
    REQUEST_NEXT_ROUND_FAILURE: 'REQUEST_NEXT_ROUND_FAILURE'
};
