export const types = {
    SET_PLAY_CARD_TIMER: 'SET_PLAY_CARD_TIMER',
    RESET_PLAY_CARD_TIMER: 'RESET_PLAY_CARD_TIMER',
    SET_VOTE_CARD_TIMER: 'SET_VOTE_CARD_TIMER',
    RESET_VOTE_CARD_TIMER: 'RESET_VOTE_CARD_TIMER',
    SET_STORYTELLER_TIMER: 'SET_STORYTELLER_TIMER',
    RESET_STORYTELLER_TIMER: 'RESET_STORYTELLER_TIMER'
};
