version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm ci
      - run:
          name: Run Client Tests
          command: npm run test:client
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  e2etest: 
    docker: 
      - image: cypress/base:10
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm ci
      - run:
          name: Start server
          command: |
            npm run build
            npm run start:testserver
          background: true
      - run:
          name: Run E2E Tests
          command: |
            mkdir -p cypress/{videos,screenshots}
            npx wait-on http://localhost:12345 && node run-cypress-test.js -r tap -- $(circleci tests split --split-by=timings <(circleci tests glob 'cypress/integration/*_spec.js'))
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  deploy-master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_MASTER_APP_NAME}.git master

  deploy-develop:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Develop to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_DEVELOP_APP_NAME}.git master


workflows:
  version: 2
  test-deploy:
    jobs:
      - e2etest
      - test
      - deploy-master:
          requires:
            - test
            - e2etest
          filters:
            branches:
              only:
                - master
      - deploy-develop:
          requires:
            - test
            - e2etest
          filters:
            branches:
              only:
                - develop
