version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  client-tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm ci
      - run:
          name: Run Client Tests
          command: npm run test:client
      - save_cache:
          key: dependency-cache-v2{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy-master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_MASTER_APP_NAME}.git master

  deploy-develop:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Develop to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_DEVELOP_APP_NAME}.git master

workflows:
  build:
    jobs:
      - client-tests
      - cypress/install:
          name: build-app
          build: npm run build
      - cypress/run:
          name: e2e-tests
          command: npx cypress run --record false --spec $((circleci tests split --split-by=timings <(circleci tests glob 'cypress/integration/*_spec.js')) | tr '\n' ',')
          requires:
            - build-app
          start: npm run start:testserver
          wait-on: 'http://localhost:12345'
          parallel: true
          parallelism: 3
          group: 3x
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: test-results/cypress
      - deploy-master:
          requires:
            - client-tests
            - e2e-tests
          filters:
            branches:
              only:
                - master
      - deploy-develop:
          requires:
            - client-tests
            - e2e-tests
          filters:
            branches:
              only:
                - develop
