version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    parallelism: 4
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm ci
      - run:
          name: Run Client Tests
          command: npm run test:client
      - run:
          name: Run E2E Tests
          command: npm run build && npm run test:e2e
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy-master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_MASTER_APP_NAME}.git master

  deploy-develop:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Develop to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_DEVELOP_APP_NAME}.git master


workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy-master:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-develop:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
