export const types = {
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_FAILURE: 'FETCH_CARDS_FAILURE',
    SELECT_CARD: 'SELECT_CARD',
    SET_PLAY_CARD: 'SET_PLAY_CARD',
    FINISH_PLAY_CARD: 'FINISH_PLAY_CARD',
    RESET_FINISH_ROUND: 'RESET_FINISH_ROUND'
};
