export const types = {
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_FAILURE: 'FETCH_CARDS_FAILURE',
    SELECT_CARD_SUCCESS: 'SELECT_CARD_SUCCESS',
    SET_PLAY_CARD: 'SET_PLAY_CARD',
    RESET_PLAYED_CARD: 'RESET_PLAYED_CARD',
    REMOVE_CARD: 'REMOVE_CARD',
};
