const statusTypes = {
    NOT_STARTED: "NOT_STARTED",
    WAITING_FOR_CURRENT_PLAYER: "WAITING_FOR_CURRENT_PLAYER",
    WAITING_FOR_OTHER_PLAYERS: "WAITING_FOR_OTHER_PLAYERS",
    WAITING_FOR_VOTES: "WAITING_FOR_VOTES",
    DISPLAY_ALL_VOTES: "DISPLAY_ALL_VOTES",
    GAME_OVER: "GAME_OVER"
};

module.exports.statusTypes = statusTypes;
