export const types = {
    RESET_STORE: 'RESET_STORE',
    AUTH_RESET: 'AUTH_RESET',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    GET_URI_SUCCESS: 'GET_URI_SUCCESS',
    GET_URI_FAILURE: 'GET_URI_FAILURE',
    LOG_OUT_FAILURE: 'LOG_OUT_FAILURE'
};
