export const types = {
    VOTE_FOR_CARD_BEGIN: 'VOTE_FOR_CARD_BEGIN',
    VOTE_FOR_CARD_SUCCESS: 'VOTE_FOR_CARD_SUCCESS',
    VOTE_FOR_CARD_FAILURE: 'VOTE_FOR_CARD_FAILURE',
    SET_VOTE_CARD: 'SET_VOTE_CARD',
    SET_VOTED_CARD: 'SET_VOTED_CARD',
    SET_PLAYED_CARDS: 'SET_PLAYED_CARDS',
    SET_MY_CARD: 'SET_MY_CARD',
    SET_ALL_VOTES: 'SET_ALL_VOTES'
};
